addons:
  apt:
    sources:
    - git-core
    packages:
    - git
script:
- |
  curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos?page={1..5} > lol.txt
- mkdir ~/bin
- wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O ~/bin/jq
- chmod +x ~/bin/jq
- |
  cat lol.txt | jq -r '.[]|select(.fork)|.full_name' | xargs -n1 -i bash -c "git clone --branch=\$(cat lol.txt | jq -r '.[]|select(.full_name==\"{}\")|.default_branch') \$(curl -H \"Authorization: token $GITHUB_TOKEN\" https://api.github.com/repos/{} | jq -r '.parent.clone_url')"
- export GITHUB_NAME=$(cat lol.txt | jq -r '.[1].owner.login' | head -1)
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- cat lol.txt | jq -r '.[]|select(.fork)|.name' | xargs -n1 -i bash -c "BRANCH=\$(cat lol.txt | jq -r '.[]|select(.name==\"{}\")|.default_branch') && cd {} && git remote add fork https://github.com/$GITHUB_NAME/{}.git && git fetch fork \$BRANCH && git push fork \$BRANCH"
notifications:
  email: false
